services:
  - type: web
    name: harvest-nation-international-bright-obeng-fianko
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: OWNER_ADMIN_EMAIL
        value: brightobengfianko@gmail.com
